// gamesData.js
const gamesData = [
  {
    team1: { name: 'India', sport: 'Cricket', image: '/images/Indianlogo.jpg' },
    team2: { name: 'England', sport: 'Cricket', image: '/images/England.webp' },
    prob1: 2.1,
    prob2: 3.2,
    prob3: 1.3,
    date: '2023-12-25',
    sportName: 'Cricket',
    tournament: 'WorldCup',
  },
  {
    team1: { name: 'Australia', sport: 'Cricket',image: '/images/AUS-logo.jpg' },
    team2: { name: 'Sri Lanka', sport: 'Cricket', image: '/images/shrilanka.png' },
    prob1: 2.1,
    prob2: 3.2,
    prob3: 1.3,
    date: '2023-12-25',
    sportName: 'Cricket',
    tournament: 'WorldCup',
  },
  {
    team1: { name: 'India', sport: 'Cricket', image: '/images/Indianlogo.jpg' },
    team2: { name: 'Sri Lanka', sport: 'Cricket', image: '/images/shrilanka.png' },
    prob1: 2.1,
    prob2: 3.2,
    prob3: 1.3,
    date: '2023-12-25',
    sportName: 'Cricket',
    tournament: 'WorldCup',
  },
  {
    team1: { name: 'Manchester City', sport: 'Football', image: '/images/ManchesterLogo.png' },
    team2: { name: 'Real Madrid', sport: 'Football', image: '/images/Real-Madrid.png' },
    prob1: 2.5,
    prob2: 3.0,
    prob3: 1.8,
    date: '2023-12-26',
    sportName: 'Football',
    tournament: 'FIFA',
  },
  {
    team1: { name: 'Crystal Palace', sport: 'Football', image: '/images/crystalpalace.png' },
    team2: { name: 'Newcastle United', sport: 'Football', image: '/images/newcastle.png' },
    prob1: 2.5,
    prob2: 3.0,
    prob3: 1.8,
    date: '2023-12-26',
    sportName: 'Football',
    tournament: 'FIFA',
  },
  {
    team1: { name: 'Spain', sport: 'Basketball', image: '/images/FC_barcelona.png' },
    team2: { name: 'USA', sport: 'Basketball', image: '/images/USA_Basketball.png' },
    prob1: 1.9,
    prob2: 2.8,
    prob3: 1.5,
    date: '2023-12-27',
    sportName: 'Basketball',
    tournament: 'NBA',
  },
  {
    team1: { name: 'Dallas Mavericks', sport: 'Basketball', image: '/images/dallasmacericks.png' },
    team2: { name: 'Argentina', sport: 'Basketball', image: '/images/Argentina.png' },
    prob1: 1.9,
    prob2: 2.8,
    prob3: 1.5,
    date: '2023-12-27',
    sportName: 'Basketball',
    tournament: 'NBA',
  },
  {
    team1: { name: 'RPG957', sport: 'esports', image: '/images/FC_barcelona.png' },
    team2: { name: 'Aptos VALOPUBG', sport: 'esports', image: '/images/USA_Basketball.png' },
    prob1: 1.9,
    prob2: 2.8,
    prob3: 1.5,
    date: '2023-12-27',
    sportName: 'esports',
    tournament: 'Dota 2',
  },
  {
    team1: { name: 'TeamX', sport: 'esports', image: '/images/TeamX_logo.png' },
    team2: { name: 'TeamY', sport: 'esports', image: '/images/TeamY_logo.png' },
    team3: { name: 'TeamZ', sport: 'esports', image: '/images/TeamZ_logo.png' },
    prob1: 2.0,
    prob2: 2.5,
    prob3: 1.7,
    date: '2023-12-28',
    sportName: 'esports',
    tournament: 'League of Legends',
  },
  {
    team1: { name: 'Gaming Giants', sport: 'esports', image: '/images/GamingGiants_logo.png' },
    team2: { name: 'Digital Dominators', sport: 'esports', image: '/images/DigitalDominators_logo.png' },
    team3: { name: 'Tech Titans', sport: 'esports', image: '/images/TechTitans_logo.png' },
    prob1: 1.8,
    prob2: 3.0,
    prob3: 2.2,
    date: '2023-12-29',
    sportName: 'esports',
    tournament: 'CS:GO Championship',
  },
  // Add more games as needed
];

export default gamesData;
